# Generated by Django 5.2.17 on 2026-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
