# Generated by Django 5.2.17 on 2026-08-16 10:50

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otpverification_email_alter_otpverification_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="email_or_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
