# Generated by Django 5.2.17 on 2026-08-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_otpverification_phone_alter_user_phone_and_more"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites",
                to="branches.branch",
            ),
        ),
    ]
