# Generated by Django 5.2.17 on 2026-08-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0003_subscription_bonus_branches_subscription_bonus_users_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
