# Generated by Django 5.2.17 on 2026-08-20 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plancomponent_planpurchase_companyplanallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSolutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDurationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('months', models.IntegerField(unique=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenDeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('price_per_branch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_hardware', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='branch_mode_scope',
            field=models.CharField(choices=[('SERVICE_BASED', 'Service-Based'), ('NON_SERVICE_BASED', 'Non-Service-Based'), ('BOTH', 'Both'), ('N_A', 'N/A')], default='BOTH', max_length=50),
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='category',
            field=models.CharField(choices=[('SOLUTION_TYPE', 'Solution Type'), ('SERVICE', 'Service'), ('OPERATOR_DESK', 'Operator Desk'), ('KIOSK', 'Kiosk'), ('TOKEN_DELIVERY', 'Token Delivery'), ('ADDON', 'Add-on'), ('BRANCH_SETUP', 'Branch Setup')], default='ADDON', max_length=50),
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='icon_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='is_addon_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='max_qty_per_branch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancomponent',
            name='pricing_type',
            field=models.CharField(choices=[('PER_UNIT', 'Per Unit'), ('FLAT', 'Flat'), ('TOGGLE_FREE', 'Toggle Free'), ('TOGGLE_PAID', 'Toggle Paid')], default='PER_UNIT', max_length=50),
        ),
        migrations.CreateModel(
            name='PriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL)),
                ('plan_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='billing.plancomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
