# Generated by Django 5.2.17 on 2026-08-20 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_data_migration'),
        ('branches', '0004_branch_mode'),
        ('companies', '0007_alter_company_logo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyplanallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companyplanallocation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='branches.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='companyplanallocation',
            unique_together={('company', 'branch', 'plan_component')},
        ),
    ]
