# Generated by Django 5.2.15 on 2026-08-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_companyplanallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendeliverymethod',
            name='queue_method_code',
            field=models.CharField(blank=True, default='', help_text="The code mapping to QueueMethod.method (e.g. '1', '2', '3', '4')", max_length=10),
        ),
    ]
