# Generated by Django 5.2.15 on 2026-08-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_data_migration_token_and_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancomponent',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
