# Generated by Django 5.2.17 on 2026-08-23 19:00

from django.db import migrations, models


def update_package_kiosk_limits(apps, schema_editor):
    Package = apps.get_model("billing", "Package")
    limits = {
        "Starter": 1,
        "Standard": 2,
        "Advanced": 3,
        "Enterprise": 5,
    }
    for name, limit in limits.items():
        Package.objects.filter(name=name).update(max_kiosks=limit)

def rollback_package_kiosk_limits(apps, schema_editor):
    Package = apps.get_model("billing", "Package")
    Package.objects.all().update(max_kiosks=0)

class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_seed_addon_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="max_kiosks",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update_package_kiosk_limits, reverse_code=rollback_package_kiosk_limits),
    ]
