# Generated by Django 5.2.15 on 2026-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_package_max_kiosks'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancomponent',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
