# Generated by Django 5.2.17 on 2026-08-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("queuing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="queuing.service",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="queuing.service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together={("branch", "service", "slot_start")},
        ),
    ]
