# Generated by Django 5.2.15 on 2026-08-21 10:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_customer_consented_at_and_more'),
        ('branches', '0004_branch_mode'),
        ('queuing', '0010_desk_is_online_booking_desk'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', encrypted_model_fields.fields.EncryptedCharField()),
                ('customer_phone_index', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('booking_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('no_show', 'No Show'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_bookings', to='branches.branch')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_bookings', to='queuing.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('max_bookings_per_slot', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='branches.branch')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='queuing.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
