# Generated by Django 5.2.15 on 2026-08-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_onlinebooking_timeslot'),
        ('companies', '0009_company_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('portal_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_color', models.CharField(default='#1E88E5', max_length=50)),
                ('display_address', models.TextField(blank=True, default='')),
                ('enabled_customer_fields', models.JSONField(blank=True, default=list)),
                ('enabled_booking_fields', models.JSONField(blank=True, default=list)),
                ('enabled_notification_channels', models.JSONField(blank=True, default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_config', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
