# Generated by Django 5.2.15 on 2026-08-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_bookingpageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='repeat_weekly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
