# Generated by Django 5.2.17 on 2026-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("queuing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="prefix",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("branch", "prefix")},
        ),
    ]
