# Generated by Django 5.2.17 on 2026-08-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuing", "0002_service_prefix_alter_service_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="desk",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("paused", "Paused"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
    ]
