# Generated by Django 5.2.17 on 2026-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuing", "0003_desk_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
