# Generated by Django 5.2.17 on 2026-08-16 10:50

import core.crypto
import encrypted_model_fields.fields
from django.db import migrations, models


def backfill_tracking_codes(apps, schema_editor):
    Ticket = apps.get_model("queuing", "Ticket")
    from core.crypto import generate_tracking_code, blind_index
    for ticket in Ticket.objects.all():
        if not ticket.tracking_code:
            ticket.tracking_code = generate_tracking_code()
        if ticket.customer_phone and not ticket.customer_phone_index:
            ticket.customer_phone_index = blind_index(ticket.customer_phone)
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ("queuing", "0004_ticket_scheduled_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="customer_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer_phone_index",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                default=core.crypto.generate_tracking_code,
                max_length=64,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_tracking_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ticket",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                default=core.crypto.generate_tracking_code,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="customer_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]

