# Generated by Django 5.2.17 on 2026-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0006_userservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='distance_at_checkin_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
