# Generated by Django 5.2.17 on 2026-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0007_ticket_distance_at_checkin_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(choices=[('qr', 'QR Scan'), ('kiosk', 'Kiosk Touch'), ('booking', 'Online Booking')], default='qr', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
