# Generated by Django 5.2.17 on 2026-08-18 10:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_waiting_tickets(apps, schema_editor):
    try:
        Ticket = apps.get_model('queuing', 'Ticket')
        Desk = apps.get_model('queuing', 'Desk')
        DeskService = apps.get_model('queuing', 'DeskService')
        CompanyPlanAllocation = apps.get_model('billing', 'CompanyPlanAllocation')
        
        from django.db.models import Sum, Q
        
        waiting_tickets = Ticket.objects.filter(status="waiting", predicted_desk__isnull=True)
        for t in waiting_tickets:
            # Check for no service mode
            no_service = False
            if t.company_id:
                try:
                    res = CompanyPlanAllocation.objects.filter(
                        company_id=t.company_id,
                        plan_component__key="services"
                    ).aggregate(total=Sum('purchased_qty'))
                    if res['total'] is not None and res['total'] == 0:
                        no_service = True
                except Exception:
                    pass

            if no_service:
                eligible_desk_ids = list(Desk.objects.filter(
                    branch_id=t.branch_id,
                    is_active=True
                ).values_list("id", flat=True))
            else:
                if not t.service_id:
                    continue
                eligible_desk_ids = list(DeskService.objects.filter(
                    service_id=t.service_id,
                    desk__branch_id=t.branch_id,
                    desk__is_active=True
                ).values_list("desk_id", flat=True))

            if not eligible_desk_ids:
                continue

            desks = list(Desk.objects.filter(id__in=eligible_desk_ids).order_by("id"))
            if not desks:
                continue

            best_desk = None
            min_load = float("inf")

            for d in desks:
                load = Ticket.objects.filter(
                    predicted_desk=d,
                    status="waiting"
                ).count()

                if load < min_load:
                    min_load = load
                    best_desk = d

            if best_desk:
                t.predicted_desk = best_desk
                t.save(update_fields=["predicted_desk"])
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Error backfilling waiting tickets: {e}")



class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0008_ticket_channel_ticket_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='predicted_desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_tickets', to='queuing.desk'),
        ),
        migrations.RunPython(backfill_waiting_tickets, reverse_code=migrations.RunPython.noop),
    ]
