# Generated by Django 5.2.15 on 2026-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0009_ticket_predicted_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='is_online_booking_desk',
            field=models.BooleanField(default=False),
        ),
    ]
