# Generated by Django 5.2.15 on 2026-08-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_channel_type'),
        ('queuing', '0010_desk_is_online_booking_desk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('last_number', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_sequences', to='branches.branch')),
            ],
            options={
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
