# Generated by Django 5.2.15 on 2026-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0011_tokensequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='source_method',
            field=models.CharField(choices=[('ON_SCREEN', 'On-Screen Booking'), ('KOT_PRINT', 'KOT Printed Token'), ('QR_SCAN', 'QR Code Scanning'), ('BOOKING', 'Online Appointment Booking'), ('COUNTER', 'Counter Issuance')], default='ON_SCREEN', max_length=20),
        ),
    ]
