# Generated by Django 5.2.15 on 2026-08-25 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_channel_type'),
        ('companies', '0009_company_solution'),
        ('queuing', '0012_ticket_source_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='KotNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS Alerts & Reminders'), ('whatsapp', 'WhatsApp Digital Tickets')], max_length=20)),
                ('recipient', models.CharField(max_length=50)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('sent_mock', 'Sent (Simulated)')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_logs', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_logs', to='companies.company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_logs', to='queuing.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KotMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS Alerts & Reminders'), ('whatsapp', 'WhatsApp Digital Tickets')], max_length=20)),
                ('template_text', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_message_templates', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_message_templates', to='companies.company')),
            ],
            options={
                'unique_together': {('branch', 'channel')},
            },
        ),
    ]
