# Generated by Django 5.2.17 on 2026-08-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsnapshot",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_snapshots",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_snapshots",
                to="companies.company",
            ),
        ),
    ]
