# Generated by Django 5.2.17 on 2026-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='geofence_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='geofence_radius_meters',
            field=models.IntegerField(default=200),
        ),
    ]
