# Generated by Django 5.2.17 on 2026-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_geofence_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='kiosk_idle_timeout_seconds',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='branch',
            name='kiosk_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
