# Generated by Django 5.2.17 on 2026-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_kiosk_idle_timeout_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='mode',
            field=models.CharField(choices=[('SERVICE_BASED', 'Service-Based'), ('NON_SERVICE_BASED', 'Non-Service-Based')], default='NON_SERVICE_BASED', max_length=50),
        ),
    ]
