# Generated by Django 5.2.15 on 2026-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='channel_type',
            field=models.CharField(choices=[('ONSITE_ONLY', 'Onsite Only'), ('ONLINE_ONLY', 'Online Only'), ('HYBRID', 'Hybrid')], default='ONSITE_ONLY', max_length=50),
        ),
    ]
