# Generated by Django 5.2.17 on 2026-08-16 10:50

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_address_company_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
