# Generated by Django 5.2.17 on 2026-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=30),
        ),
    ]
