# Generated by Django 5.2.17 on 2026-08-17 11:04

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_onboarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='support_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
