# Generated by Django 5.2.17 on 2026-08-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_support_email_company_support_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
