# Generated by Django 5.2.15 on 2026-08-21 10:39

from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    from django.utils.text import slugify
    for c in Company.objects.all():
        if not c.slug:
            base_slug = slugify(c.name)
            if not base_slug:
                base_slug = "company"
            slug = base_slug
            counter = 1
            while Company.objects.filter(slug=slug).exclude(id=c.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            c.slug = slug
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs),
    ]
