# Generated by Django 5.2.15 on 2026-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='solution',
            field=models.CharField(default='ONSITE_ONLINE', max_length=50),
        ),
    ]
