/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySlugRouteImport } from './routes/$companySlug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LiveDemoRouteImport } from './routes/live-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CompanySlugLoginRouteImport } from './routes/$companySlug.login'
import { Route as DisplayBranchIdRouteImport } from './routes/display.$branchId'
import { Route as KioskBranchIdRouteImport } from './routes/kiosk.$branchId'
import { Route as KotBranchIdRouteImport } from './routes/kot.$branchId'
import { Route as QBranchIdRouteImport } from './routes/q.$branchId'
import { Route as TTicketIdRouteImport } from './routes/t.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemoRoute = LiveDemoRouteImport.update({
  id: '/live-demo',
  path: '/live-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugLoginRoute = CompanySlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CompanySlugRoute,
} as any)
const DisplayBranchIdRoute = DisplayBranchIdRouteImport.update({
  id: '/display/$branchId',
  path: '/display/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskBranchIdRoute = KioskBranchIdRouteImport.update({
  id: '/kiosk/$branchId',
  path: '/kiosk/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const KotBranchIdRoute = KotBranchIdRouteImport.update({
  id: '/kot/$branchId',
  path: '/kot/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const QBranchIdRoute = QBranchIdRouteImport.update({
  id: '/q/$branchId',
  path: '/q/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TTicketIdRoute = TTicketIdRouteImport.update({
  id: '/t/$ticketId',
  path: '/t/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/display/$branchId': typeof DisplayBranchIdRoute
  '/kiosk/$branchId': typeof KioskBranchIdRoute
  '/kot/$branchId': typeof KotBranchIdRoute
  '/q/$branchId': typeof QBranchIdRoute
  '/t/$ticketId': typeof TTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/display/$branchId': typeof DisplayBranchIdRoute
  '/kiosk/$branchId': typeof KioskBranchIdRoute
  '/kot/$branchId': typeof KotBranchIdRoute
  '/q/$branchId': typeof QBranchIdRoute
  '/t/$ticketId': typeof TTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/display/$branchId': typeof DisplayBranchIdRoute
  '/kiosk/$branchId': typeof KioskBranchIdRoute
  '/kot/$branchId': typeof KotBranchIdRoute
  '/q/$branchId': typeof QBranchIdRoute
  '/t/$ticketId': typeof TTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$companySlug'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/live-demo'
    | '/login'
    | '/partnerships'
    | '/pricing'
    | '/services'
    | '/signup'
    | '/$companySlug/login'
    | '/display/$branchId'
    | '/kiosk/$branchId'
    | '/kot/$branchId'
    | '/q/$branchId'
    | '/t/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$companySlug'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/live-demo'
    | '/login'
    | '/partnerships'
    | '/pricing'
    | '/services'
    | '/signup'
    | '/$companySlug/login'
    | '/display/$branchId'
    | '/kiosk/$branchId'
    | '/kot/$branchId'
    | '/q/$branchId'
    | '/t/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/$companySlug'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/live-demo'
    | '/login'
    | '/partnerships'
    | '/pricing'
    | '/services'
    | '/signup'
    | '/$companySlug/login'
    | '/display/$branchId'
    | '/kiosk/$branchId'
    | '/kot/$branchId'
    | '/q/$branchId'
    | '/t/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanySlugRoute: typeof CompanySlugRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveDemoRoute: typeof LiveDemoRoute
  LoginRoute: typeof LoginRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  DisplayBranchIdRoute: typeof DisplayBranchIdRoute
  KioskBranchIdRoute: typeof KioskBranchIdRoute
  KotBranchIdRoute: typeof KotBranchIdRoute
  QBranchIdRoute: typeof QBranchIdRoute
  TTicketIdRoute: typeof TTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug': {
      id: '/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demo': {
      id: '/live-demo'
      path: '/live-demo'
      fullPath: '/live-demo'
      preLoaderRoute: typeof LiveDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/login': {
      id: '/$companySlug/login'
      path: '/login'
      fullPath: '/$companySlug/login'
      preLoaderRoute: typeof CompanySlugLoginRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/display/$branchId': {
      id: '/display/$branchId'
      path: '/display/$branchId'
      fullPath: '/display/$branchId'
      preLoaderRoute: typeof DisplayBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/$branchId': {
      id: '/kiosk/$branchId'
      path: '/kiosk/$branchId'
      fullPath: '/kiosk/$branchId'
      preLoaderRoute: typeof KioskBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kot/$branchId': {
      id: '/kot/$branchId'
      path: '/kot/$branchId'
      fullPath: '/kot/$branchId'
      preLoaderRoute: typeof KotBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$branchId': {
      id: '/q/$branchId'
      path: '/q/$branchId'
      fullPath: '/q/$branchId'
      preLoaderRoute: typeof QBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$ticketId': {
      id: '/t/$ticketId'
      path: '/t/$ticketId'
      fullPath: '/t/$ticketId'
      preLoaderRoute: typeof TTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompanySlugRouteChildren {
  CompanySlugLoginRoute: typeof CompanySlugLoginRoute
}

const CompanySlugRouteChildren: CompanySlugRouteChildren = {
  CompanySlugLoginRoute: CompanySlugLoginRoute,
}

const CompanySlugRouteWithChildren = CompanySlugRoute._addFileChildren(
  CompanySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanySlugRoute: CompanySlugRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveDemoRoute: LiveDemoRoute,
  LoginRoute: LoginRoute,
  PartnershipsRoute: PartnershipsRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  DisplayBranchIdRoute: DisplayBranchIdRoute,
  KioskBranchIdRoute: KioskBranchIdRoute,
  KotBranchIdRoute: KotBranchIdRoute,
  QBranchIdRoute: QBranchIdRoute,
  TTicketIdRoute: TTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
