# Generated by Django 5.2.17 on 2026-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
